name: Default Envs
on: [push]
jobs:
  print-envs:
    runs-on: ubuntu-latest
    steps:
      - run: echo GITHUB_WORKFLO - $GITHUB_WORKFLOW
      - run: echo GITHUB_ACTION - $GITHUB_ACTION
      - run: echo GITHUB_ACTOR - $GITHUB_ACTOR
      - run: echo GITHUB_REPOSITORY - $GITHUB_REPOSITORY
      - run: echo GITHUB_EVENT_NAME - $GITHUB_EVENT_NAME
      - run: echo GITHUB_EVENT_PATH - $GITHUB_EVENT_PATH
      - run: echo GITHUB_WORKSPACE - $GITHUB_WORKSPACE
      - run: echo GITHUB_SHA - $GITHUB_SHA
      - run: echo GITHUB_REF - $GITHUB_REF
      - run: echo HOME - $HOME
